name: deployment

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      - self-hosted
      - deployment-server

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Set up Docker Buildu
      #   uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trucksan:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/trucksan:latest

  pull:
    needs: build
    runs-on:
      - self-hosted
      - deployment-server
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/trucksan:latest

  deploy:
    needs: pull
    runs-on:
      - self-hosted
      - deployment-server

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Docker run container
      #   run: docker run --name restaurant-portal-dev -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-portal

      - name: Run Docker compose
        run: docker-compose -f "docker-compose.yml" up -d --build
